-- Grants UI schema — operational entities on top of the SF-mirror grants table.
-- Five new tables + one addition to grants.
-- Reference: docs/superpowers/specs/2026-04-24-grants-ui-design.md §3

create extension if not exists "pgcrypto";

-- ========== grant_reports ==========
-- Simple tracking: due date, submitted date, notes. The uploaded file of the
-- submitted report lives in grant_attachments with report_id set.

create table grant_reports (
  id uuid primary key default gen_random_uuid(),
  grant_id text not null references grants(id) on delete cascade,
  name text not null,
  due_date date not null,
  submitted_date date,
  notes text,
  status text not null default 'not_started'
    check (status in ('not_started','in_progress','submitted','waived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index grant_reports_grant_id_idx on grant_reports(grant_id, due_date);
create index grant_reports_due_unsubmitted_idx
  on grant_reports(due_date)
  where submitted_date is null;

-- ========== grant_tasks ==========

create table grant_tasks (
  id uuid primary key default gen_random_uuid(),
  grant_id text not null references grants(id) on delete cascade,
  label text not null,
  due_date date,
  completed_at timestamptz,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index grant_tasks_grant_id_idx on grant_tasks(grant_id);

-- ========== grant_attachments ==========
-- Supabase Storage bucket: "grant-attachments" (private, signed-URL access).
-- report_id is nullable — only set when the file is a report's submission.

create table grant_attachments (
  id uuid primary key default gen_random_uuid(),
  grant_id text not null references grants(id) on delete cascade,
  report_id uuid references grant_reports(id) on delete set null,
  filename text not null,
  storage_path text not null,
  content_type text not null,
  size_bytes bigint not null,
  category text,
  uploaded_at timestamptz not null default now()
);

create index grant_attachments_grant_id_idx on grant_attachments(grant_id);
create index grant_attachments_report_id_idx
  on grant_attachments(report_id)
  where report_id is not null;

-- ========== grant_notes ==========

create table grant_notes (
  id uuid primary key default gen_random_uuid(),
  grant_id text not null references grants(id) on delete cascade,
  body text not null,
  author text not null default 'admin',
  created_at timestamptz not null default now()
);

create index grant_notes_grant_id_idx on grant_notes(grant_id, created_at desc);

-- ========== field_definitions ==========
-- Metadata for user-added custom fields on grants.
-- Keys are prefixed 'cf_' to keep custom columns visually distinct from SF-mirror
-- columns. Adding a row here does NOT create the column — a separate reconciliation
-- step (run from the POST /api/grants/field-definitions handler) runs the ALTER
-- inside the same transaction.

create table field_definitions (
  id uuid primary key default gen_random_uuid(),
  key text unique not null
    check (key ~ '^cf_[a-z0-9_]{2,40}$'),
  label text not null,
  field_type text not null
    check (field_type in (
      'text','long_text','number','currency','date','bool','select','multi_select'
    )),
  options jsonb,
  sort_order int not null default 0,
  is_hidden_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index field_definitions_sort_order_idx on field_definitions(sort_order);

-- ========== grants: last_synced_snapshot ==========
-- Captures the values last pushed to SF so the sync modal can compute a reliable
-- diff. Populated on every successful sync-to-SF operation.

alter table grants add column last_synced_snapshot jsonb;

-- ========== updated_at triggers ==========
-- set_updated_at() was created by 0001_create_grants_schema.sql and dropped by
-- 0004_grants_sf_mirror.sql along with the rest of v1. Recreate it here.

create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger grant_reports_set_updated_at
  before update on grant_reports
  for each row execute function set_updated_at();

create trigger field_definitions_set_updated_at
  before update on field_definitions
  for each row execute function set_updated_at();

-- ========== Storage bucket ==========
-- Creating via the supabase.storage schema. Bucket is private; access is via
-- signed URLs generated by the API.

insert into storage.buckets (id, name, public, file_size_limit)
values ('grant-attachments', 'grant-attachments', false, 52428800)
on conflict (id) do nothing;
